### ISSUE TITLE
Missing 'atlas' folder

### ISSUE THREAD

**Issue by vertikalm** [GuvaCode/TrueSpace#1]
Hello, I'm curious to see this project running. The build was successful, but the program hangs on the loading screen because the /binary/textures/atlas folder is missing.

**Comment by GuvaCode** [comment]
Yes, that's right, there is no folder with resources so
as they are with a non-open license.

Write your email and I will give you a link to the folder with resources

**Comment by vertikalm** [comment]
mail sent, thx
clossing...

**Comment by GuvaCode** [comment]
https://drive.google.com/drive/folders/1ukt91adoKDXkdks3uNmKXxUuRQshAu-j?usp=sharing

вт, 16 апр. 2024 г. в 18:17, vertikalm ***@***.***>:
